# Site settings
title: Howard's Blog
email: howardxchen@gmail.com
description: "Developer Blog"
baseurl: ""
url: "http://chenhoward.com"
twitter_username: jekyllrb
github_username: chenhoward

# Build settings
markdown: kramdown
permalink: pretty
