# Site settings
title: "Howard Chen: Pointers and Stacks"
email: howardxchen@gmail.com
description: "Blogging about my developer experience"
baseurl: ""
url: "http://chenhoward.com"
twitter_username: chowybear
github_username: chenhoward

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
